"""Check that a SCHISM image runs workspaces generated by rompy-schism.

Generates three short models from the test data (a mesh of the southern Great
Barrier Reef with M2, S2 and N2 tides) and runs them in the image under MPI:

- 2d: barotropic tides, depth averaged;
- 3d: barotropic tides on the 47-level test vgrid.in;
- wwm: 2d tides and ERA5 winds, coupled with WWM driven by WAVEWATCH III spectra;
- hotstart: 2d tides writing hotstart files every hour, then merged with
  combine_hotstart7.

SCHISM exits with status 0 even when it aborts, so a run passes only when
mirror.out ends with "Run completed successfully", fatal.error is empty and the
expected outputs are NetCDF files.

Usage: python docker/test_image.py <image>
"""

import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

from rompy.core.data import DataBlob
from rompy.core.source import SourceFile, SourceIntake
from rompy.core.time import TimeRange
from rompy.core.types import DatasetCoords
from rompy.model import ModelRun

from rompy_schism.boundary_core import TidalDataset
from rompy_schism.config import SCHISMConfig
from rompy_schism.data import (
    BoundarySetupWithSource,
    SCHISMData,
    SCHISMDataBoundaryConditions,
    SCHISMDataSflux,
    SCHISMDataWave,
    SfluxAir,
)
from rompy_schism.grid import SCHISMGrid
from rompy_schism.namelists import NML, Param
from rompy_schism.namelists.wwminput import Wwminput

TESTS = Path(__file__).resolve().parents[1] / "tests"
DATA = TESTS / "data"
NETCDF_MAGIC = (b"CDF", b"\x89HDF")


def tides() -> TidalDataset:
    database = DATA / "schism" / "tides"
    if not (database / "oceanum-atlas").exists():
        with tarfile.open(database / "oceanum-atlas.tar.gz") as tar:
            tar.extractall(database)
    return TidalDataset(
        tidal_database=database,
        tidal_model="OCEANUM-atlas",
        constituents=["M2", "S2", "N2"],
        extrapolate_tides=True,
    )


def config(vgrid=None, wave=False, hotstart=False) -> SCHISMConfig:
    """A barotropic tidal model: 3D with a vgrid, with WWM waves if wave is set,
    writing hotstart files every hour if hotstart is set."""
    grid = SCHISMGrid(
        hgrid=DataBlob(source=DATA / "schism" / "hgrid.gr3"),
        drag=2.5e-3,
        **({"vgrid": DataBlob(source=vgrid)} if vgrid else {}),
    )
    boundary = SCHISMDataBoundaryConditions(
        tidal_data=tides(),
        boundaries={0: BoundarySetupWithSource(elev_type=3, vel_type=3)},
    )
    schout = {"iof_hydro__1": 1, "iof_hydro__26": 1 if vgrid else 0}
    core = {"ibc": 1, "ibtp": 0, "dt": 150.0, "nspool": 24, "ihfskip": 1152}
    if hotstart:
        core["ihfskip"] = 24  # hotstart output needs nhot_write multiple of ihfskip
    data = {"boundary_conditions": boundary}
    nml = {}
    if wave:
        data["atmos"] = SCHISMDataSflux(
            air_1=SfluxAir(
                source=SourceFile(uri=DATA / "schism" / "era5.nc"),
                uwind_name="u10",
                vwind_name="v10",
                prmsl_name="msl",
                filter={"sort": {"coords": ["latitude"]}},
            )
        )
        data["wave"] = SCHISMDataWave(
            id="wavedata",
            source=SourceIntake(
                catalog_uri=DATA / "catalog.yaml", dataset_id="ausspec"
            ),
            coords=DatasetCoords(t="time", x="lon", y="lat", z="depth"),
        )
        nml["wwminput"] = Wwminput(proc={"deltc": 600})
        schout.update({"iof_wwm__1": 1, "iof_wwm__9": 1})
    return SCHISMConfig(
        grid=grid,
        data=SCHISMData(**data),
        nml=NML(
            param=Param(
                core=core,
                opt={"nstep_wwm": 4} if wave else {},
                schout=schout,
            ),
            **nml,
        ),
    )


# name: (config, command); scribes: 1 for the 2D outputs + zCoordinates (+ 2 for
# the 3D velocity)
CASES = {
    "2d": (config(), ["mpirun", "-n", "4", "schism", "2"]),
    "3d": (
        config(vgrid=DATA / "schism" / "vgrid.in"),
        ["mpirun", "-n", "6", "schism", "4"],
    ),
    "wwm": (config(wave=True), ["mpirun", "-n", "4", "schism_wwm", "2"]),
    "hotstart": (config(hotstart=True), ["mpirun", "-n", "4", "schism", "2"]),
}


def is_netcdf(path: Path) -> bool:
    return path.exists() and path.read_bytes()[:4].startswith(NETCDF_MAGIC)


def check(workspace: Path) -> list[str]:
    """Problems with a finished run, from SCHISM's own log and error files."""
    outputs = workspace / "outputs"
    problems = []
    mirror = outputs / "mirror.out"
    if not mirror.exists() or "Run completed successfully" not in mirror.read_text():
        problems.append("mirror.out does not report a completed run")
    fatal = outputs / "fatal.error"
    if fatal.exists() and fatal.read_text().strip():
        problems.append(f"fatal.error: {fatal.read_text().strip()[:500]}")
    if not is_netcdf(outputs / "out2d_1.nc"):
        problems.append("no out2d_1.nc")
    return problems


def main(image: str) -> int:
    # Importing the test configuration downloads the test data if it is missing
    sys.path.insert(0, str(TESTS))
    import conftest  # noqa: F401

    period = TimeRange(start="2023-01-01T00", end="2023-01-01T03", interval="1h")
    failed = []
    with tempfile.TemporaryDirectory() as tmp:
        for name, (case, command) in CASES.items():
            run = ModelRun(run_id=name, period=period, output_dir=tmp, config=case)
            workspace = Path(run()).resolve()
            if name == "hotstart":
                # Hotstart output every 24 steps. Set in the file: Schout's check of
                # nhot=1 fails on released versions (rom-py/rompy-schism#19)
                param = workspace / "param.nml"
                text = param.read_text().replace("nhot = 0", "nhot = 1")
                param.write_text(text.replace("nhot_write = 8640", "nhot_write = 24"))
            result = subprocess.run(
                ["docker", "run", "--rm", "-v", f"{workspace}:/data", image, *command],
                capture_output=True,
                text=True,
                check=False,
            )
            problems = check(workspace)
            if name == "hotstart" and not problems:
                # Merge the per-process hotstart files of time step 24 (1 hour)
                subprocess.run(
                    ["docker", "run", "--rm", "-v", f"{workspace}:/data", "-w",
                     "/data/outputs", image, "combine_hotstart7", "-i", "24"],
                    capture_output=True,
                    check=False,
                )  # fmt: skip
                if not is_netcdf(workspace / "outputs" / "hotstart_it=24.nc"):
                    problems.append("combine_hotstart7 wrote no hotstart_it=24.nc")
            print(f"{name}: {'OK' if not problems else 'FAILED'}")
            if problems:
                print(*problems, result.stdout[-2000:], result.stderr[-2000:], sep="\n")
                failed.append(name)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1]))
